/*
Copyright 2026 Scott Friedman

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package github generates GitHub Actions release workflow files for bagboy projects.
package github

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/scttfrdmn/bagboy/pkg/cicd"
	"github.com/scttfrdmn/bagboy/pkg/config"
)

func init() {
	cicd.Register(New())
}

// Provider generates GitHub Actions pipeline files.
type Provider struct{}

// New returns a new GitHub Actions Provider.
func New() *Provider {
	return &Provider{}
}

// Name returns "github".
func (p *Provider) Name() string { return "github" }

// GeneratePipeline produces a .github/workflows/release.yml file.
func (p *Provider) GeneratePipeline(cfg *config.Config) ([]cicd.File, error) {
	content, err := p.renderWorkflow(cfg)
	if err != nil {
		return nil, fmt.Errorf("github actions pipeline: %w", err)
	}
	return []cicd.File{
		{Path: ".github/workflows/release.yml", Content: content},
	}, nil
}

func (p *Provider) renderWorkflow(cfg *config.Config) (string, error) {
	const workflowTmpl = `# GitHub Actions release workflow generated by bagboy
# https://github.com/scttfrdmn/bagboy

name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
{{- if .HasNode}}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
{{- end}}
{{- if .HasRust}}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
{{- end}}

      - name: Install bagboy
        run: go install github.com/scttfrdmn/bagboy/cmd/bagboy@latest

      - name: Build binaries
        run: make build-all

      - name: Pack all formats
        run: bagboy pack --all

      - name: Publish release
        run: bagboy publish
        env:
          GITHUB_TOKEN: ${{"{{"}} secrets.GITHUB_TOKEN {{"}}"}}
{{- if .HasSigning}}

      - name: Sign binaries
        run: bagboy sign --all
        env:
          COSIGN_EXPERIMENTAL: "1"
{{- end}}
`

	data := struct {
		*config.Config
		HasNode    bool
		HasRust    bool
		HasSigning bool
	}{
		Config:     cfg,
		HasNode:    false,
		HasRust:    false,
		HasSigning: cfg != nil && cfg.Signing.Sigstore.Enabled,
	}

	t, err := template.New("workflow").Parse(workflowTmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
