package installer

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/scttfrdmn/bagboy/pkg/config"
)

type Packager struct{}

func New() *Packager {
	return &Packager{}
}

func (p *Packager) Name() string {
	return "installer"
}

func (p *Packager) Validate(cfg *config.Config) error {
	if cfg.Installer.BaseURL == "" {
		return fmt.Errorf("installer.base_url is required")
	}
	return nil
}

func (p *Packager) Pack(ctx context.Context, cfg *config.Config) (string, error) {
	tmpl := `#!/bin/bash
set -e

# {{.Name}} installer script
# Generated by bagboy

# Detection
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
[[ "$ARCH" == "x86_64" ]] && ARCH="amd64"
[[ "$ARCH" == "aarch64" ]] && ARCH="arm64"

# Config
VERSION="${VERSION:-{{.Version}}}"
BASE_URL="{{.BaseURL}}"
BIN_NAME="{{.Name}}"
INSTALL_PATH="${INSTALL_PATH:-{{.InstallPath}}}"

# Determine binary name
case "$OS" in
  darwin)
    BINARY_NAME="${BIN_NAME}-${OS}-${ARCH}"
    ;;
  linux)
    BINARY_NAME="${BIN_NAME}-${OS}-${ARCH}"
    ;;
  *)
    echo "Unsupported OS: $OS"
    exit 1
    ;;
esac

DOWNLOAD_URL="${BASE_URL}/${BINARY_NAME}"

echo "Installing ${BIN_NAME} ${VERSION}..."
echo "Downloading from: ${DOWNLOAD_URL}"

# Download
curl -fsSL "$DOWNLOAD_URL" -o "/tmp/${BIN_NAME}"
chmod +x "/tmp/${BIN_NAME}"

{{if .VerifyChecksum}}
# Verify checksum (if available)
if command -v sha256sum >/dev/null 2>&1; then
  CHECKSUMS_URL="${BASE_URL}/checksums.txt"
  if curl -fsSL "$CHECKSUMS_URL" -o "/tmp/checksums.txt" 2>/dev/null; then
    cd /tmp
    if sha256sum -c checksums.txt --ignore-missing 2>/dev/null | grep -q "${BIN_NAME}"; then
      echo "✓ Checksum verified"
    else
      echo "⚠ Checksum verification failed, but continuing..."
    fi
  fi
fi
{{end}}

# Install (with sudo if needed)
if [[ -w "$INSTALL_PATH" ]]; then
    mv "/tmp/${BIN_NAME}" "${INSTALL_PATH}/${BIN_NAME}"
else
    echo "Installing to ${INSTALL_PATH} (requires sudo)"
    sudo mv "/tmp/${BIN_NAME}" "${INSTALL_PATH}/${BIN_NAME}"
fi

echo "✓ Installed ${BIN_NAME} to ${INSTALL_PATH}/${BIN_NAME}"
echo ""
echo "Run '${BIN_NAME} --help' to get started!"`

	t, err := template.New("installer").Parse(tmpl)
	if err != nil {
		return "", err
	}

	data := struct {
		*config.Config
		BaseURL        string
		InstallPath    string
		VerifyChecksum bool
	}{
		Config:         cfg,
		BaseURL:        cfg.Installer.BaseURL,
		InstallPath:    cfg.Installer.InstallPath,
		VerifyChecksum: cfg.Installer.VerifyChecksum,
	}

	outputPath := filepath.Join("dist", "install.sh")
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return "", err
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	if err := t.Execute(f, data); err != nil {
		return "", err
	}

	// Make executable
	if err := os.Chmod(outputPath, 0755); err != nil {
		return "", err
	}

	return outputPath, nil
}
