/*
Copyright 2026 Scott Friedman

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package gitlab generates GitLab CI pipeline files for bagboy projects.
package gitlab

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/scttfrdmn/bagboy/pkg/cicd"
	"github.com/scttfrdmn/bagboy/pkg/config"
)

func init() {
	cicd.Register(New())
}

// Provider generates GitLab CI pipeline files.
type Provider struct{}

// New returns a new GitLab CI Provider.
func New() *Provider {
	return &Provider{}
}

// Name returns "gitlab".
func (p *Provider) Name() string { return "gitlab" }

// GeneratePipeline produces a .gitlab-ci.yml file.
func (p *Provider) GeneratePipeline(cfg *config.Config) ([]cicd.File, error) {
	content, err := p.renderPipeline(cfg)
	if err != nil {
		return nil, fmt.Errorf("gitlab ci pipeline: %w", err)
	}
	return []cicd.File{
		{Path: ".gitlab-ci.yml", Content: content},
	}, nil
}

func (p *Provider) renderPipeline(cfg *config.Config) (string, error) {
	const pipelineTmpl = `# GitLab CI pipeline generated by bagboy
# https://github.com/scttfrdmn/bagboy

image: golang:1.24

stages:
  - build
  - pack
  - release

variables:
  CGO_ENABLED: "0"
  GOFLAGS: "-mod=readonly"

cache:
  paths:
    - .go/pkg/mod/

before_script:
  - export GOPATH="$CI_PROJECT_DIR/.go"
  - go install github.com/scttfrdmn/bagboy/cmd/bagboy@latest

build:
  stage: build
  script:
    - make build-all
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - tags

pack:
  stage: pack
  needs: [build]
  script:
    - bagboy pack --all
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - tags

release:
  stage: release
  needs: [pack]
  script:
    - bagboy publish
  only:
    - tags
  environment:
    name: production
`

	data := struct {
		*config.Config
	}{
		Config: cfg,
	}

	t, err := template.New("pipeline").Parse(pipelineTmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
