package rpm

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/scttfrdmn/bagboy/pkg/config"
)

type Packager struct{}

func New() *Packager {
	return &Packager{}
}

func (p *Packager) Name() string {
	return "rpm"
}

func (p *Packager) Validate(cfg *config.Config) error {
	if cfg.Packages.RPM.Vendor == "" {
		return fmt.Errorf("rpm.vendor is required")
	}
	return nil
}

func (p *Packager) Pack(ctx context.Context, cfg *config.Config) (string, error) {
	// Find Linux binary
	var linuxBinary string
	for arch, path := range cfg.Binaries {
		if strings.HasPrefix(arch, "linux-") {
			linuxBinary = path
			break
		}
	}
	if linuxBinary == "" {
		return "", fmt.Errorf("no Linux binary found")
	}

	specContent := p.generateSpec(cfg, linuxBinary)

	outputPath := filepath.Join("dist", fmt.Sprintf("%s-%s-1.x86_64.rpm", cfg.Name, cfg.Version))
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return "", err
	}

	// Create spec file
	specPath := filepath.Join("dist", cfg.Name+".spec")
	if err := os.WriteFile(specPath, []byte(specContent), 0644); err != nil {
		return "", err
	}

	// Create mock RPM (in real implementation, would use rpmbuild)
	mockRpm := fmt.Sprintf("# Mock RPM package for %s %s\n# Generated by bagboy\n# In production, this would be built with rpmbuild\n", cfg.Name, cfg.Version)
	if err := os.WriteFile(outputPath, []byte(mockRpm), 0644); err != nil {
		return "", err
	}

	return outputPath, nil
}

func (p *Packager) generateSpec(cfg *config.Config, binaryPath string) string {
	tmpl := `Name:           {{.Name}}
Version:        {{.Version}}
Release:        1%{?dist}
Summary:        {{.Description}}
License:        {{.License}}
URL:            {{.Homepage}}
Source0:        %{name}-%{version}.tar.gz
BuildArch:      x86_64
Group:          {{.Group}}
Vendor:         {{.Vendor}}

%description
{{.Description}}

%prep
%setup -q

%build
# No build needed for pre-compiled binary

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/usr/bin
cp {{.BinaryName}} $RPM_BUILD_ROOT/usr/bin/{{.Name}}

%files
/usr/bin/{{.Name}}

%changelog
* $(date "+%a %b %d %Y") {{.Vendor}} - {{.Version}}-1
- Initial package`

	t, _ := template.New("spec").Parse(tmpl)

	data := struct {
		*config.Config
		Group      string
		Vendor     string
		BinaryName string
	}{
		Config:     cfg,
		Group:      cfg.Packages.RPM.Group,
		Vendor:     cfg.Packages.RPM.Vendor,
		BinaryName: filepath.Base(binaryPath),
	}

	if data.Group == "" {
		data.Group = "Applications/System"
	}

	var result strings.Builder
	t.Execute(&result, data)
	return result.String()
}
